version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coashy
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: coachy-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/coashy
      JWT_SECRET: supersecretjwt
      PORT: 5001
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app           
      - /usr/src/app/node_modules        
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

